config/routes.rb
Rails.application.routes.draw do
  resources :stats
  resources :setlist_items
  devise_for :users
  resources :transitions
  resources :setlists
  resources :songs
  resources :venues
  resources :tours
  resources :shows
  resources :set_types
  resources :footnote_symbols
  resources :people
  resources :bandmembers
  resources :albums
  resources :artists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "songs#index"
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_one_attached :cover
  validates :artist_id, :title, :release_date, presence: true
  has_many :songs

  before_save :generate_slug, :set_lastmod

  private
  
  def set_lastmod
    self.lastmod = Time.current if self.lastmod.nil?
  end

  def generate_slug
    if self.title.present? 
      self.slug = self.title.parameterize
    else
      errors.add(:title, "can't be blank")
    end
  end
end

app/models/artist.rb
class Artist < ApplicationRecord
    before_save :generate_slug
    
    has_many :albums
    has_many :songs
  
    private
  
    def generate_slug
      self.slug = name.parameterize if slug.blank?
    end
  end  

app/models/bandmember.rb
class Bandmember < ApplicationRecord
  belongs_to :artist
  belongs_to :people

  validates :role, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :bandmembers, dependent: :destroy
  
    validates :personname, presence: true
    validates :slug, presence: true, uniqueness: true
    validates :notes, presence: true
    validates :appearances, presence: true
  end
  

app/models/set_type.rb
class SetType < ApplicationRecord
    validates :settype, presence: true, uniqueness: true
  end
  

app/models/setlist.rb
class Setlist < ApplicationRecord
    belongs_to :song
    belongs_to :show
  
    # Add validations if needed
    validates :displayname, presence: true
    validates :setnumber, presence: true
    validates :position, presence: true
    # etc.
  end
  

app/models/setlist_item.rb
class SetlistItem < ApplicationRecord
  belongs_to :setlist
  belongs_to :song
end

app/models/show.rb
class Show < ApplicationRecord
    belongs_to :artist
    belongs_to :venue
    belongs_to :tour, optional: true

    has_many :setlists
  
    validates :venue_id, presence: true
    validates :artist_id, presence: true
    validates :showdate, presence: true
    validates :showorder, presence: true
    validates :settype, presence: true
    validates :opener, presence: true
    validates :soundcheck, presence: true
    validates :permalink, presence: true
  end
  

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :album, optional: true

  before_save :generate_slug
  
  validates :name, :slug, :artist, presence: true

  private

  def generate_slug
    if self.name.present? 
      self.slug = self.name.parameterize
    else
      errors.add(:name, "can't be blank")
    end
  end
end

app/models/stat.rb
class Stat < ApplicationRecord
  belongs_to :user
end

app/models/tour.rb
class Tour < ApplicationRecord
    validates :tourname, presence: true, uniqueness: true
  end
  

app/models/transition.rb
class Transition < ApplicationRecord
    validates :transition, presence: true, length: { maximum: 3 }
    validates :dropdown, presence: true, length: { maximum: 20 }
    validates :default_transition, presence: true, length: { maximum: 20 }
    validates :desc, presence: true, length: { maximum: 55 }
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
    validates :venuename, presence: true
    validates :slug, uniqueness: true, allow_nil: true
  end
  

app/controllers/transitions_controller.rb
class TransitionsController < ApplicationController
  before_action :set_transition, only: %i[ show edit update destroy ]

  # GET /transitions or /transitions.json
  def index
    @transitions = Transition.all
  end

  # GET /transitions/1 or /transitions/1.json
  def show
  end

  # GET /transitions/new
  def new
    @transition = Transition.new
  end

  # GET /transitions/1/edit
  def edit
  end

  # POST /transitions or /transitions.json
  def create
    @transition = Transition.new(transition_params)

    respond_to do |format|
      if @transition.save
        format.html { redirect_to transition_url(@transition), notice: "Transition was successfully created." }
        format.json { render :show, status: :created, location: @transition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transitions/1 or /transitions/1.json
  def update
    respond_to do |format|
      if @transition.update(transition_params)
        format.html { redirect_to transition_url(@transition), notice: "Transition was successfully updated." }
        format.json { render :show, status: :ok, location: @transition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transitions/1 or /transitions/1.json
  def destroy
    @transition.destroy!

    respond_to do |format|
      format.html { redirect_to transitions_url, notice: "Transition was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transition
      @transition = Transition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transition_params
      params.require(:transition).permit(:transition, :dropdown, :default_transition, :desc, :updated_at)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/transitions_helper.rb
module TransitionsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/transitions/_form.html.erb
<%= form_with(model: transition) do |form| %>
  <% if transition.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transition.errors.count, "error") %> prohibited this transition from being saved:</h2>

      <ul>
        <% transition.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :transition, style: "display: block" %>
    <%= form.text_field :transition %>
  </div>

  <div>
    <%= form.label :dropdown, style: "display: block" %>
    <%= form.text_field :dropdown %>
  </div>

  <div>
    <%= form.label :default_transition, style: "display: block" %>
    <%= form.text_field :default_transition %>
  </div>

  <div>
    <%= form.label :desc, style: "display: block" %>
    <%= form.text_field :desc %>
  </div>

  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <%= form.datetime_field :updated_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transitions/_transition.html.erb
<div id="<%= dom_id transition %>">
  <p>
    <strong>Transition:</strong>
    <%= transition.transition %>
  </p>

  <p>
    <strong>Dropdown:</strong>
    <%= transition.dropdown %>
  </p>

  <p>
    <strong>Default transition:</strong>
    <%= transition.default_transition %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= transition.desc %>
  </p>

  <p>
    <strong>Updated at:</strong>
    <%= transition.updated_at %>
  </p>

</div>

app/views/transitions/edit.html.erb
<% content_for :title, "Editing transition" %>

<h1>Editing transition</h1>

<%= render "form", transition: @transition %>

<br>

<div>
  <%= link_to "Show this transition", @transition %> |
  <%= link_to "Back to transitions", transitions_path %>
</div>

app/views/transitions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Transitions" %>

<h1>Transitions</h1>

<div id="transitions">
  <% @transitions.each do |transition| %>
    <%= render transition %>
    <p>
      <%= link_to "Show this transition", transition %>
    </p>
  <% end %>
</div>

<%= link_to "New transition", new_transition_path %>

app/views/transitions/new.html.erb
<% content_for :title, "New transition" %>

<h1>New transition</h1>

<%= render "form", transition: @transition %>

<br>

<div>
  <%= link_to "Back to transitions", transitions_path %>
</div>

app/views/transitions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transition %>

<div>
  <%= link_to "Edit this transition", edit_transition_path(@transition) %> |
  <%= link_to "Back to transitions", transitions_path %>

  <%= button_to "Destroy this transition", @transition, method: :delete %>
</div>