config/routes.rb
Rails.application.routes.draw do
  resources :stats
  resources :setlist_items
  devise_for :users
  resources :transitions
  resources :setlists
  resources :songs
  resources :venues
  resources :tours
  resources :shows
  resources :set_types
  resources :footnote_symbols
  resources :people
  resources :bandmembers
  resources :albums
  resources :artists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "songs#index"
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_one_attached :cover
  validates :artist_id, :title, :release_date, presence: true
  has_many :songs

  before_save :generate_slug, :set_lastmod

  private
  
  def set_lastmod
    self.lastmod = Time.current if self.lastmod.nil?
  end

  def generate_slug
    if self.title.present? 
      self.slug = self.title.parameterize
    else
      errors.add(:title, "can't be blank")
    end
  end
end

app/models/artist.rb
class Artist < ApplicationRecord
    before_save :generate_slug
    
    has_many :albums
    has_many :songs
  
    private
  
    def generate_slug
      self.slug = name.parameterize if slug.blank?
    end
  end  

app/models/bandmember.rb
class Bandmember < ApplicationRecord
  belongs_to :artist
  belongs_to :people

  validates :role, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :bandmembers, dependent: :destroy
  
    validates :personname, presence: true
    validates :slug, presence: true, uniqueness: true
    validates :notes, presence: true
    validates :appearances, presence: true
  end
  

app/models/set_type.rb
class SetType < ApplicationRecord
    validates :settype, presence: true, uniqueness: true
  end
  

app/models/setlist.rb
class Setlist < ApplicationRecord
    belongs_to :song
    belongs_to :show
  
    # Add validations if needed
    validates :displayname, presence: true
    validates :setnumber, presence: true
    validates :position, presence: true
    # etc.
  end
  

app/models/setlist_item.rb
class SetlistItem < ApplicationRecord
  belongs_to :setlist
  belongs_to :song
end

app/models/show.rb
class Show < ApplicationRecord
    belongs_to :artist
    belongs_to :venue
    belongs_to :tour, optional: true

    has_many :setlists
  
    validates :venue_id, presence: true
    validates :artist_id, presence: true
    validates :showdate, presence: true
    validates :showorder, presence: true
    validates :settype, presence: true
    validates :opener, presence: true
    validates :soundcheck, presence: true
    validates :permalink, presence: true
  end
  

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :album, optional: true

  before_save :generate_slug
  
  validates :name, :slug, :artist, presence: true

  private

  def generate_slug
    if self.name.present? 
      self.slug = self.name.parameterize
    else
      errors.add(:name, "can't be blank")
    end
  end
end

app/models/stat.rb
class Stat < ApplicationRecord
  belongs_to :user
end

app/models/tour.rb
class Tour < ApplicationRecord
    validates :tourname, presence: true, uniqueness: true
  end
  

app/models/transition.rb
class Transition < ApplicationRecord
    validates :transition, presence: true, length: { maximum: 3 }
    validates :dropdown, presence: true, length: { maximum: 20 }
    validates :default_transition, presence: true, length: { maximum: 20 }
    validates :desc, presence: true, length: { maximum: 55 }
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
    validates :venuename, presence: true
    validates :slug, uniqueness: true, allow_nil: true
  end
  

app/controllers/api/v1/setlists_controller.rb
module Api
  module V1
    class SetlistsController < ApplicationController
      def index
        @setlists = Setlist.all
        render json: @setlists
      end
    end
  end
end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController
  before_action :set_setlist, only: %i[ show edit update destroy ]

  # GET /setlists or /setlists.json
  def index
    @setlists = Setlist.all
  end

  # GET /setlists/1 or /setlists/1.json
  def show
  end

  # GET /setlists/new
  def new
    @setlist = Setlist.new
  end

  # GET /setlists/1/edit
  def edit
  end

  # POST /setlists or /setlists.json
  def create
    @setlist = Setlist.new(setlist_params)

    respond_to do |format|
      if @setlist.save
        format.html { redirect_to setlist_url(@setlist), notice: "Setlist was successfully created." }
        format.json { render :show, status: :created, location: @setlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setlists/1 or /setlists/1.json
  def update
    respond_to do |format|
      if @setlist.update(setlist_params)
        format.html { redirect_to setlist_url(@setlist), notice: "Setlist was successfully updated." }
        format.json { render :show, status: :ok, location: @setlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setlists/1 or /setlists/1.json
  def destroy
    @setlist.destroy!

    respond_to do |format|
      format.html { redirect_to setlists_url, notice: "Setlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setlist
      @setlist = Setlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setlist_params
      params.require(:setlist).permit(:show_id, :song_id, :displayname, :setnumber, :position, :transition_id, :footnote, :tracktime, :isjam, :isreprise, :uniqueid, :isjamchart, :jamchartnote)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/api/v1/setlists_helper.rb
module Api::V1::SetlistsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/setlists_helper.rb
module SetlistsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/setlists/_form.html.erb
<%= form_with(model: setlist) do |form| %>
  <% if setlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(setlist.errors.count, "error") %> prohibited this setlist from being saved:</h2>

      <ul>
        <% setlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :show_id, style: "display: block" %>
    <%= form.number_field :show_id %>
  </div>

  <div>
    <%= form.label :song_id, style: "display: block" %>
    <%= form.number_field :song_id %>
  </div>

  <div>
    <%= form.label :displayname, style: "display: block" %>
    <%= form.text_field :displayname %>
  </div>

  <div>
    <%= form.label :setnumber, style: "display: block" %>
    <%= form.text_area :setnumber %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.label :transition_id, style: "display: block" %>
    <%= form.number_field :transition_id %>
  </div>

  <div>
    <%= form.label :footnote, style: "display: block" %>
    <%= form.text_field :footnote %>
  </div>

  <div>
    <%= form.label :tracktime, style: "display: block" %>
    <%= form.text_field :tracktime %>
  </div>

  <div>
    <%= form.label :isjam, style: "display: block" %>
    <%= form.number_field :isjam %>
  </div>

  <div>
    <%= form.label :isreprise, style: "display: block" %>
    <%= form.number_field :isreprise %>
  </div>

  <div>
    <%= form.label :uniqueid, style: "display: block" %>
    <%= form.text_field :uniqueid %>
  </div>

  <div>
    <%= form.label :isjamchart, style: "display: block" %>
    <%= form.number_field :isjamchart %>
  </div>

  <div>
    <%= form.label :jamchartnote, style: "display: block" %>
    <%= form.text_field :jamchartnote %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/setlists/_setlist.html.erb
<div id="<%= dom_id setlist %>">
  <p>
    <strong>Show:</strong>
    <%= setlist.show_id %>
  </p>

  <p>
    <strong>Song:</strong>
    <%= setlist.song_id %>
  </p>

  <p>
    <strong>Displayname:</strong>
    <%= setlist.displayname %>
  </p>

  <p>
    <strong>Setnumber:</strong>
    <%= setlist.setnumber %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= setlist.position %>
  </p>

  <p>
    <strong>Transition:</strong>
    <%= setlist.transition_id %>
  </p>

  <p>
    <strong>Footnote:</strong>
    <%= setlist.footnote %>
  </p>

  <p>
    <strong>Tracktime:</strong>
    <%= setlist.tracktime %>
  </p>

  <p>
    <strong>Isjam:</strong>
    <%= setlist.isjam %>
  </p>

  <p>
    <strong>Isreprise:</strong>
    <%= setlist.isreprise %>
  </p>

  <p>
    <strong>Uniqueid:</strong>
    <%= setlist.uniqueid %>
  </p>

  <p>
    <strong>Isjamchart:</strong>
    <%= setlist.isjamchart %>
  </p>

  <p>
    <strong>Jamchartnote:</strong>
    <%= setlist.jamchartnote %>
  </p>

</div>

app/views/setlists/edit.html.erb
<% content_for :title, "Editing setlist" %>

<h1>Editing setlist</h1>

<%= render "form", setlist: @setlist %>

<br>

<div>
  <%= link_to "Show this setlist", @setlist %> |
  <%= link_to "Back to setlists", setlists_path %>
</div>

app/views/setlists/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Setlists" %>

<h1>Setlists</h1>

<div id="setlists">
  <% @setlists.each do |setlist| %>
    <%= render setlist %>
    <p>
      <%= link_to "Show this setlist", setlist %>
    </p>
  <% end %>
</div>

<%= link_to "New setlist", new_setlist_path %>

app/views/setlists/new.html.erb
<% content_for :title, "New setlist" %>

<h1>New setlist</h1>

<%= render "form", setlist: @setlist %>

<br>

<div>
  <%= link_to "Back to setlists", setlists_path %>
</div>

app/views/setlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @setlist %>

<div>
  <%= link_to "Edit this setlist", edit_setlist_path(@setlist) %> |
  <%= link_to "Back to setlists", setlists_path %>

  <%= button_to "Destroy this setlist", @setlist, method: :delete %>
</div>